--PROYECTO:  PRY_REMETFU
--FECHA   :  2022/03/07
--AREA    :  DMI

USE [master]
GO

IF EXISTS (SELECT * FROM sysdatabases WHERE (name = 'MDMQ_REMETFU')) 
BEGIN
	PRINT 'LA BASE DE DATOS EXISTE...BORRANDO'
    DROP DATABASE MDMQ_REMETFU
END
GO

CREATE DATABASE MDMQ_REMETFU
GO

USE MDMQ_REMETFU
GO

CREATE SCHEMA Remetfu
GO

ALTER DATABASE MDMQ_REMETFU
ADD FILEGROUP REMETFU_IDX;
GO

ALTER DATABASE MDMQ_REMETFU
ADD FILE
(
  NAME = 'MDMQ_REMETFU.ndf',

  --Segun el servidor
  FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\MDMQ_REMETFU_idx.ndf' , --Ruperto
  --FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MDMQ_REMETFU.ndf',  --equipo de desarrollo
  --FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\MDMQ_REMETFU.ndf' --en mi maquina
  SIZE = 5MB,
  MAXSIZE = 100MB,
  FILEGROWTH = 5MB
)
TO FILEGROUP REMETFU_IDX
go
